workflows:
  ios-workflow:
    name: iOS Build
    environment:
      xcode: latest
      flutter: stable
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
      - name: Build IPA
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/*.app
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
    max_build_duration: 60




