import 'package:flutter/material.dart';
import 'contact_screen.dart';

class PrivacyScreen extends StatelessWidget {
  const PrivacyScreen({super.key});

  static const String lastUpdated = '7 October 2026';

  static const List<(String, List<String>)> _sections = [
    (
      'Information We Collect',
      [
        'Account details: your name and email address.',
        'Birth details: date, time and place of birth (and coordinates) for you and any family members you add.',
        'Chat content: questions you ask the AI Astrologer and messages exchanged with Pandits.',
        'Wallet activity: recharges and consultation charges.',
        'Basic device and usage data needed to keep the app working reliably.',
      ],
    ),
    (
      'How We Use Your Information',
      [
        'To calculate your Kundli, Dasha periods, Panchang and personalised predictions.',
        'To provide AI readings and connect you with live Pandits.',
        'To maintain your wallet balance and consultation history.',
        'To improve accuracy, reliability and safety of CosmicGuide.',
      ],
    ),
    (
      'Sharing',
      [
        'We do not sell your personal information.',
        'Your chart is shared with a Pandit only during a consultation you start.',
        'AI readings may be generated by trusted AI service providers who process your question and chart data on our behalf.',
        'We may disclose information when required by law.',
      ],
    ),
    (
      'Data Security',
      [
        'Data is transmitted over encrypted connections.',
        'Passwords are stored as secure hashes, never in plain text.',
        'Access to personal data is limited to what is needed to run the service.',
      ],
    ),
    (
      'Your Rights',
      [
        'Access and update your birth details from your profile at any time.',
        'Request a copy of your data or deletion of your account by contacting us.',
        'Withdraw consent for optional communications at any time.',
      ],
    ),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFFCF7F1),
      appBar: AppBar(
        backgroundColor: const Color(0xFFFCF7F1),
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_ios_new, color: Colors.black),
          tooltip: 'Back',
          onPressed: () => Navigator.maybePop(context),
        ),
        title: const Text('Privacy Policy', style: TextStyle(color: Colors.black, fontWeight: FontWeight.bold)),
        centerTitle: true,
      ),
      body: SafeArea(
        top: false,
        child: ListView(
          padding: const EdgeInsets.all(16),
          children: [
            const Text(
              'CosmicGuide respects your privacy. This policy explains what we collect, why, and the choices you have.',
              style: TextStyle(fontSize: 14, height: 1.5, color: Colors.black87),
            ),
            const SizedBox(height: 16),
            for (final s in _sections) ...[
              LegalSection(title: s.$1, items: s.$2, icon: Icons.privacy_tip_outlined),
              const SizedBox(height: 12),
            ],
            LegalContactCard(
              title: 'Contact Us',
              text: 'For privacy questions or data requests, write to ${CosmicGuideContact.privacyEmail}.',
              buttonLabel: 'Email Privacy Team',
              onPressed: () => CosmicGuideContact.email(
                context,
                to: CosmicGuideContact.privacyEmail,
                subject: '[CosmicGuide] Privacy request',
              ),
            ),
            const SizedBox(height: 16),
            const Text(
              'Last updated: $lastUpdated. We will notify you in the app of any material changes to this policy.',
              style: TextStyle(fontSize: 12, color: Colors.grey, fontStyle: FontStyle.italic),
            ),
          ],
        ),
      ),
    );
  }
}

class LegalSection extends StatelessWidget {
  final String title;
  final List<String> items;
  final IconData icon;

  const LegalSection({super.key, required this.title, required this.items, required this.icon});

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: Colors.grey.shade200),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(title, style: const TextStyle(fontSize: 17, fontWeight: FontWeight.bold, color: Colors.black)),
          const SizedBox(height: 10),
          ...items.map((item) => Padding(
                padding: const EdgeInsets.only(bottom: 8),
                child: Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Padding(
                      padding: const EdgeInsets.only(top: 2),
                      child: Icon(icon, color: const Color(0xFFFB9548), size: 16),
                    ),
                    const SizedBox(width: 8),
                    Expanded(child: Text(item, style: const TextStyle(fontSize: 14, height: 1.45, color: Colors.black87))),
                  ],
                ),
              )),
        ],
      ),
    );
  }
}

class LegalContactCard extends StatelessWidget {
  final String title;
  final String text;
  final String buttonLabel;
  final VoidCallback onPressed;

  const LegalContactCard({super.key, required this.title, required this.text, required this.buttonLabel, required this.onPressed});

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: const Color(0xFFFFF6E5),
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: const Color(0xFFFB9548).withValues(alpha: 0.3)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(title, style: const TextStyle(fontSize: 17, fontWeight: FontWeight.bold)),
          const SizedBox(height: 6),
          Text(text, style: const TextStyle(fontSize: 14, height: 1.45, color: Colors.black87)),
          const SizedBox(height: 12),
          OutlinedButton.icon(
            onPressed: onPressed,
            icon: const Icon(Icons.email_outlined, size: 18, color: Color(0xFFFB9548)),
            label: Text(buttonLabel, style: const TextStyle(color: Colors.black)),
            style: OutlinedButton.styleFrom(
              backgroundColor: Colors.white,
              side: const BorderSide(color: Color(0xFFFB9548)),
              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
            ),
          ),
        ],
      ),
    );
  }
}
